//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team3a_LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanRecord
    {
        public int LoanNumber { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> DateBorrowed { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string LoadStatus { get; set; }
        public Nullable<decimal> OverdueFines { get; set; }
        public string Remark { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
    }
}
