//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team3a_LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.LoanRecords = new HashSet<LoanRecord>();
        }
    
        public int MemberID { get; set; }
        public string MumberName { get; set; }
        public string Addresses { get; set; }
        public string City { get; set; }
        public Nullable<int> Contact { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public Nullable<int> BooksBorrowed { get; set; }
        public string UserID { get; set; }
        public string PassWords { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanRecord> LoanRecords { get; set; }
    }
}
